version: "3.7"

services:
    # image project
    app:
        container_name: market-hub-api
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # postgres
    db:
        container_name: market-hub-postgres
        image: postgres:15.4
        environment:
            POSTGRES_DB: markethub
            POSTGRES_PASSWORD: markethub
            POSTGRES_USER: markethub
        ports:
            - 5432:5432
        networks:
            - laravel

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "user@user.com.br"
            PGADMIN_DEFAULT_PASSWORD: "1234"
        ports:
            - "16543:80"
        depends_on:
            - db
        networks:
            - laravel

networks:
    laravel:
        driver: bridge